/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Function;

import GUI.LOGIN;

/**
 *
 * @author ADMIN
 */
public class Manager extends javax.swing.JFrame {

    /**
     * Creates new form Manager
     */
    public Manager() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DSM = new javax.swing.JButton();
        DV = new javax.swing.JButton();
        DOANHTHU = new javax.swing.JButton();
        TT = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Logout = new javax.swing.JCheckBoxMenuItem();
        Exit = new javax.swing.JCheckBoxMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setTitle("QUẢN LÝ");

        DSM.setBackground(new java.awt.Color(0, 102, 204));
        DSM.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DSM.setForeground(new java.awt.Color(255, 255, 255));
        DSM.setText("Danh Sách Máy");
        DSM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DSMActionPerformed(evt);
            }
        });

        DV.setBackground(new java.awt.Color(0, 102, 204));
        DV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DV.setForeground(new java.awt.Color(255, 255, 255));
        DV.setText("Dịch Vụ");
        DV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DVActionPerformed(evt);
            }
        });

        DOANHTHU.setBackground(new java.awt.Color(0, 102, 204));
        DOANHTHU.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DOANHTHU.setForeground(new java.awt.Color(255, 255, 255));
        DOANHTHU.setText("Doanh Thu");
        DOANHTHU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DOANHTHUActionPerformed(evt);
            }
        });

        TT.setBackground(new java.awt.Color(0, 102, 204));
        TT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TT.setForeground(new java.awt.Color(255, 255, 255));
        TT.setText("Tính Tiền");
        TT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TTActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        Logout.setSelected(true);
        Logout.setText("Đăng xuất");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        jMenu1.add(Logout);

        Exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.ALT_DOWN_MASK));
        Exit.setSelected(true);
        Exit.setText("Thoát");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        jMenu1.add(Exit);

        jMenuItem1.setText("Danh sách Nhân Viên");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DSM)
                    .addComponent(DOANHTHU, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TT, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {DOANHTHU, DSM, DV, TT});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DSM)
                    .addComponent(DV))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TT)
                    .addComponent(DOANHTHU))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {DOANHTHU, DSM, DV, TT});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
         System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        new LOGIN().setVisible(true);
        this.hide();
    }//GEN-LAST:event_LogoutActionPerformed

    private void DSMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DSMActionPerformed
         new DANHSACHMAY().setVisible(true);
         this.hide();
    }//GEN-LAST:event_DSMActionPerformed

    private void DVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DVActionPerformed
       new DICHVU().setVisible(true);
       this.hide();
    }//GEN-LAST:event_DVActionPerformed

    private void DOANHTHUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DOANHTHUActionPerformed
       new DOANHTHU().setVisible(true);
       this.hide();
    }//GEN-LAST:event_DOANHTHUActionPerformed

    private void TTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TTActionPerformed
         new TINHTIEN().setVisible(true);
         this.hide();
    }//GEN-LAST:event_TTActionPerformed
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new DANHSACHNHANVIEN().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DOANHTHU;
    private javax.swing.JButton DSM;
    private javax.swing.JButton DV;
    private javax.swing.JCheckBoxMenuItem Exit;
    private javax.swing.JCheckBoxMenuItem Logout;
    private javax.swing.JButton TT;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
